overrides:
  "@types/react": 19.3.0
  "@types/react-dom": 19.3.0

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - electron-to-chromium

allowBuilds:
  sharp: true
  unrs-resolver: true
