overrides:
  "@types/react": 19.2.17
  "@types/react-dom": 19.2.3

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - electron-to-chromium

allowBuilds:
  sharp: true
  unrs-resolver: true
